export enum ActionTypes {
    SET_REMINDER = "SET_REMINDER",
    SET_REMINDERS = "SET_REMINDERS",
    SET_REMINDERS_FOR_DATE = "SET_REMINDERS_FOR_DATE",
    SET_REMINDERS_FOR_DATE_YEAR_AND_MONTH = "SET_REMINDERS_FOR_DATE_YEAR_AND_MONTH",
    SET_REMINDERS_GROUPED_BY_DATE = "SET_REMINDERS_GROUPED_BY_DATE",
    SET_REMINDER_CREATED_FLAG = "SET_REMINDER_CREATED_FLAG",
    SET_REMINDER_UPDATED_FLAG = "SET_REMINDER_UPDATED_FLAG",
    SET_REMINDER_DELETED_FLAG = "SET_REMINDER_DELETED_FLAG",
    RESET_REMINDER_FLAGS = "RESET_REMINDER_FLAGS"
}