export enum ActionTypes {
    SET_REMINDER = "SET_REMINDER",
    SET_REMINDERS = "SET_REMINDERS",
    SET_REMINDERS_FOR_DATE = "SET_REMINDERS_FOR_DATE",
    SET_REMINDER_CREATED_FLAG = "SET_REMINDER_CREATED_FLAG",
    SET_REMINDER_UPDATED_FLAG = "SET_REMINDER_UPDATED_FLAG",
    SET_REMINDER_DELETED_FLAG = "SET_REMINDER_DELETED_FLAG",
    SET_REMINDER_TITLE_VALIDATION_FLAG = "SET_REMINDER_TITLE_VALIDATION_FLAG",
    SET_REMINDER_DATE_TIME_VALIDATION_FLAG = "SET_REMINDER_DATE_VALIDATION_FLAG",
    SET_REMINDER_DATE_TIME_OVERLAP_VALIDATION_FLAG = "SET_REMINDER_DATE_TIME_OVERLAP_VALIDATION_FLAG",
    SET_REMINDER_CITY_VALIDATION_FLAG = "SET_REMINDER_CITY_VALIDATION_FLAG",
    RESET_REMINDER_FLAGS = "RESET_REMINDER_FLAGS"
}